
[window]
padding = {x=3, y=8}
opacity = 0.8
blur = true

[font]
normal = {family = "Fira Code", style = "Regular"}
size = 11

[general]
import = [
    "~/.config/alacritty/themes/themes/nord.toml"
]

[keyboard]
bindings = [
{key = "m", mods = "Control", chars = "|"}
]
